### ISSUE TITLE
Comment support

### ISSUE THREAD

**Issue by suntong** [mengzhuo/yaml-to-go#4]
First of all, thanks a lot for providing such a useful tool!

I'm coming here wishing that comments might be supported in future. I.e., for a yaml like:

```yaml
web:

  # Port to listen on
  port: 3000
  # Enable prefork in Production?
  prod: false
````

The comment can be copied to the generated struct definition as well. 

thanks
